<html>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

<link rel="stylesheet" href="vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="vendor/hover/hover.min.css">
<link rel="stylesheet" href="vendor/animate/animate.css">
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet'  type='text/css'>
<link rel="stylesheet" type="text/css" href="src/style/main.css">
<!-- Optional theme -->
<link rel="stylesheet" href="vendor/bootstrap/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="src/js/lib/bootstrap/js/bootstrap.min.js"></script>

<body>

<h1> Pages </h1>

<h2> Work <a> Edit </a> </h2>

<h2> About <a> Edit Text </a> </h2>

<h2> Contact <a> Edit Text </a> </h2>

<h2> More <a> Edit Text </a> </h2>

</body>

</html>
