<html>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

<link rel="stylesheet" href="../../vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="../../vendor/hover/hover.min.css">
<link rel="stylesheet" href="../../vendor/animate/animate.css">
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet'  type='text/css'>
<link rel="stylesheet" type="text/css" href="../style/main.css">
<!-- Optional theme -->
<link rel="stylesheet" href="../../vendor/bootstrap/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="../js/lib/bootstrap/js/bootstrap.min.js"></script>

<script src = "../js/lib/vue.js"></script>

<body>
<div class="container" id="app">

	<div class="row">
		<div class="col-md-6 backButton">
			<span @click="back" class="glyphicon glyphicon-chevron-left animated" aria-hidden="true"> </span>
		</div>
	</div>

	<div class="row">
		<div class="col-md-4 col-md-offset-4 centered">
			<img src="<?= $image ?>" class="blogImage" ></img>
		</di>
	</div>


</div>



</body>
<script src="../js/app/blog.js"></script>
</html>
