<html>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

<link rel="stylesheet" href="/styles/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="/styles/hover.min.css">
<link rel="stylesheet" href="/styles/animate.css">
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet'  type='text/css'>
<link rel="stylesheet" type="text/css" href="/styles/main.css">
<!-- Optional theme -->
<link rel="stylesheet" href="/styles/bootstrap/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="/scripts/lib/bootstrap/js/bootstrap.min.js"></script>

<script src = "/scripts/lib/vue.js"></script>
<body>
<div id='app'>

<h1> Add Work Item </h1>

<div v-for="workPiece in workPieces">
	<workitem :item="workPiece"></workitem>
	<editModal :item="workPiece"></editModal>
</div>


</div>
</body>


<!-- template for the modal component -->
<template id="editmodal">
  <div class="modal-mask" v-show="item.showModal" transition="modal">
    <div class="modal-wrapper">
      <div class="modal-container">

        <div class="modal-header">
          <slot name="header">
            Edit {{ item.name }}
          </slot>
        </div>

        <div class="modal-body">
          <slot name="body">
            default body
          </slot>
        </div>

        <div class="modal-footer">
          <slot name="footer">
            default footer
            <button class="modal-default-button"
              @click="show = false">
              OK
            </button>
          </slot>
        </div>
      </div>
    </div>
  </div>
</template>

<template id="workitem">
	<div>
      <h2> {{ item.title }} <a @click='item.showModal = true;'> Edit </a> <a href='#'> Delete </a> </h2>
	</div>
</template>


<script src="/scripts/app/addWorkPiece.js"></script>

</html>
