<html>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

<link rel="stylesheet" href="styles/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="styles/hover.min.css">
<link rel="stylesheet" href="styles/animate.css">
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet'  type='text/css'>
<link rel="stylesheet" type="text/css" href="styles/main.css">
<!-- Optional theme -->
<link rel="stylesheet" href="styles/bootstrap/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="scripts/lib/bootstrap/js/bootstrap.min.js"></script>

<script src = "scripts/lib/vue.js"></script>
<body>
<div id='app'>

<h1> Pages </h1>

<administerpage :page="about"></administerpage>
<administerpage :page="work"></administerpage>
<administerpage :page="contact"></administerpage>
<administerpage :page="more"></administerpage>

</div>
</body>


<template id="administerpage">
	<div>
      <h2> {{ page.name }} <a href='admin/{{ page.id }}'> Edit </a> </h2>
	</div>
</template>

<script src="scripts/app/admin.js"></script>

</html>
