<html>
<head>
<meta charset="UTF-8">
<meta name="description" content="India Pearce Illustration Design">
<meta name="keywords" content="HTML,CSS,XML,JavaScript">
<meta name="author" content="India Pearce">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<link rel="stylesheet" href="../styles/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="../styles/hover.min.css">
<link rel="stylesheet" href="../styles/animate.css">
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet'  type='text/css'>
<link rel="stylesheet" type="text/css" href="../styles/main.css">
<!-- Optional theme -->
<link rel="stylesheet" href="../styles/bootstrap/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="../scripts/lib/bootstrap/js/bootstrap.min.js"></script>

<script src = "../scripts/lib/vue.js"></script>

<body>
<?php include_once("../analyticstracking.php") ?>

<div class="container" id="app">


	<div class="col-xs-4 backButton">
		<div>
			<span @click="back" class="glyphicon glyphicon-chevron-left animated" aria-hidden="true"></span>
		</div>
	</div>


	<div class="workitem">
		<img src="<?= $image ?>" class="blogImage"></img>
		<div class="blogtext">
			<u class="blogTitle"><span class="blogTitleSpan"><h1> <?= $title ?> </h1></span></u>
			<?= $content ?>
		</div>
	</div>



</div>



</body>
<script src="../scripts/app/blog.js"></script>
</html>
